### ISSUE TITLE
xmlstats.exe: different versions here and in XmlNotepad?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [clovett/tools#17]
Hi Chris
this version here shows another header (e.g. V1.09) and other options then the same file in XmlNotepad (e.g. 2.8.0.65). Is it intended?

**Comment by clovett** [comment]
Yes, xmlstats.exe has it's own version number.

**Comment by Pierre-de-la-Verre** [comment]
But the functions from the version in XMLNotepad are better - right?

**Comment by clovett** [comment]
I see, you are right, I merged those changes from XML Notepad 
and released new bits here:
https://github.com/clovett/tools/releases/tag/v1.0.2

**Comment by Pierre-de-la-Verre** [comment]
Thanks, fixed.
